services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
  nginx:
    image: nginx:1.15
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
      - nginx
    links:
      - mysql
      - nginx