services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d    
    env_file:
      - ./sql/.env

  nginx:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www/html
      - ./nginx/conf.d/:/etc/nginx/conf.d/

  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/var/www/html

networks:
  app-network:
    driver: bridge